fork_me_ribbon_url: https://github.com/qchemlab-embedding/2023-07-14-workshop
baseurl: "/2023-07-14-workshop"
title: "Introduction to the qchemlab-embedding project"

source: .
destination: ./_site
layouts_dir: ./jekyll-common/layouts
includes_dir: ./jekyll-common/includes

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'codehilite'

include: ['jekyll-common/pages']
exclude: ['LICENSE']

collections:
  episodes:
    output: true
    permalink: /:name/
